services:
  backend:
    image: erenisci/rag-implementation:backend
    ports:
      - '8000:8000'
    restart: unless-stopped

  frontend:
    image: erenisci/rag-implementation:frontend
    ports:
      - '5173:3000'
    depends_on:
      - backend
    restart: unless-stopped
