services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - '5173:3000'
    depends_on:
      - backend
    restart: unless-stopped
